### ISSUE TITLE
 save measures to BIM file Error

### ISSUE THREAD

**Issue by ArmanFalah** [DaxEditor/DaxEditor#3]
Dear Marco
I am using visual studio 2015 and when I want to save measures to BIM file, I receive this error.
I guess the problem is related to Translation.

Thank you in advance.

12/11/2016 7:06:43 PM
DAX Editor version: 2.0.1611.1901
Exception message:
An internal error has occured.
Exception stack:
   at Microsoft.AnalysisServices.Tabular.Utils.SerializeSparseCollection(IEnumerable`1 sparseCollection, SparseSerializerSettings settings)
   at Microsoft.AnalysisServices.Tabular.ObjectTranslationCollection.SerializeToJsonObject()
   at Microsoft.AnalysisServices.Tabular.Culture.SerializeAdditionalDataToJsonObject(JsonObject jsonObj, SerializeOptions options, Int32 dbCompatibilityLevel)
   at Microsoft.AnalysisServices.Tabular.Culture.SerializeToJsonObject(JsonObject result, SerializeOptions options, Int32 dbCompatibilityLevel)
   at Microsoft.AnalysisServices.Tabular.Model.<>c__DisplayClass76.<SerializeToJsonObject>b__66(Culture obj)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.AnalysisServices.Tabular.Model.SerializeToJsonObject(JsonObject result, SerializeOptions options, Int32 dbCompatibilityLevel)
   at Microsoft.AnalysisServices.Tabular.Database.SerializeToJsonObject(JsonObject result, SerializeOptions options)
   at Microsoft.AnalysisServices.Tabular.Database.SerializeToNewJsonObject(SerializeOptions options)
   at Microsoft.AnalysisServices.Tabular.JsonSerializer.SerializeDatabase(Database database, SerializeOptions options)
   at DaxEditor.Json.JsonUtilities.Serialize(Database database)
   at DaxEditor.MeasuresContainer.UpdateMeasuresInJson(String inputJson)
   at DaxEditor.BimFileIntegration.SaveMeasuresToBimFile(String daxFilePath)
   at DaxEditor.DaxEditorPackage.EditAdvancedSaveBimFileContentCommandExecute(Object sender, EventArgs e)

**Comment by marcosqlbi** [comment]
We're not able to reproduce the issue. Can you send us a BIM file that can reproduce the problem (I suggest you to create a small example that you can share).
Thanks!

**Comment by ArmanFalah** [comment]
[RMN_Model.txt](https://github.com/DaxEditor/DaxEditor/files/646781/RMN_Model.txt)

**Comment by marcosqlbi** [comment]
Ok thanks, we'll investigate on it!

**Comment by marcosqlbi** [comment]
It should work now, please confirm!

**Comment by ArmanFalah** [comment]
Unfortunately, it does not work.
I used the same file that I sent you, but it steel does not work.
I can "save measures to BIM file", but when I want to open the BIM file I get this error:


============================
Error Message:
============================

An error occurred while opening the model on the workspace database. Reason: Property 'Measure' of object 'perspective measure' refers to an object which cannot be found.

============================
Call Stack:
============================

   at Microsoft.AnalysisServices.VSHost.VSHostManager.PrepareSandbox(Boolean newProject, Boolean& isRefreshNeeded, Boolean& isImpersonationChanged, Boolean& saveRequired, List`1& truncatedTables, Boolean isRealTimeMode, Int32 clientCompatibilityLevel)
   at Microsoft.AnalysisServices.VSHost.Integration.EditorFactory.CreateEditorInstance(UInt32 grfCreateDoc, String pszMkDocument, String pszPhysicalView, IVsHierarchy pvHier, UInt32 itemid, IntPtr punkDocDataExisting, IntPtr& ppunkDocView, IntPtr& ppunkDocData, String& pbstrEditorCaption, Guid& pguidCmdUI, Int32& pgrfCDW)

============================

Thanks.

**Comment by marcosqlbi** [comment]
Strange, it didn't produce this error to me. Did you update DAX Editor? What is the version you are using?

**Comment by ArmanFalah** [comment]
Yes, I updated. I am using latest version 2.0.1701.2501.
I guess the error is related to Perspective, because when I delete all Perspective, it works properly.
I send you the corrupted BIM file. it couldn't be opened in VS.
[RMN_Model_Error.txt](https://github.com/DaxEditor/DaxEditor/files/706771/RMN_Model_Error.txt)

**Comment by marcosqlbi** [comment]
Can you try to send a model that works and describe after which operation the model doesn't work? I tried to repro creating a perspective on a model I have but it is not enough to break the model.
Thanks!

**Comment by ArmanFalah** [comment]
I am sure that the error is related to Perspective. you get the error when you want to delete a measure in DAX file that exist in a perspective.
I am sending you the model. 
as you can see, you have a perspective that contain just "Cost Amount" Measure.
if you remove "Cost Amount" Measuer from DAX file, you will get the error.
you can delete "# SKUs" Measure in DAX file properly, because it is not in any perspective.
Thanks.
[RMN_Model_Perspective.txt](https://github.com/DaxEditor/DaxEditor/files/719516/RMN_Model_Perspective.txt)

**Comment by marcosqlbi** [comment]
Ok I see - the steps to reproduce the issue are:
1) Open the BIM file you sent in Visual Studio (the .TXT must be replaced with .BIM)
2) Get measures from BIM file
3) Remove the "Cost Amount" measure from the DAX file
4) Same measures to BIM file
5) Open the BIM file

The file is corrupted at this point because the perspective has a reference to a measure that no longer exists.
Thus, when a measure is removed from the model, it has to be removed also from all the perspectives referencing it. I am wondering whether this is an issue of the TOM library, but we'll investigate.
Thanks!

**Comment by marcosqlbi** [comment]
We just released a version of DAX Editor that solved the problem. Just update DAX Editor in Visual Studio.

**Comment by ArmanFalah** [comment]
I just checked. it works perfect :)
Thank you for your attention to this matter.
