### ISSUE TITLE
Error Extracting Measures in SSDT 14.0.61704.140 in SQL 2014 (1103) models

### ISSUE THREAD

**Issue by jpresley15** [DaxEditor/DaxEditor#8]
I've used DAX Editor to extract measures with no problems on SQL 2014 (1103) models using SSDT 14.0.61021.0 but I receive an error when extracting measures from the BIM file when using SSDT 14.0.61704.140 which currently is the latest version. 
Using the latest SSDT, I have the same model created twice, one in compatibility level SQL 2014 (1103) and the other in SQL 2016 (1200). Only the SQL 2016 (1200) model will extract measures from the BIM and the SQL 2014 version fails when trying to extract measures.

Attached is the error I receive when trying to extract measures from the SQL 2014 version BIM.
[DAX Editor Error.txt](https://github.com/DaxEditor/DaxEditor/files/997726/DAX.Editor.Error.txt)

**Comment by HavenDV** [comment]
I will fix it on Monday. Need to update used libraries to latest version

**Comment by jpresley15** [comment]
HavenDV, I'm not sure if you're still planning on applying a fix to this issue.  I noticed SQL Server Data Tools build 14.0.61705.170 has the same issue.  Thanks.

**Comment by HavenDV** [comment]
I updated the SSDT, updated the dependencies of the package, all the tests pass:
https://github.com/DaxEditor/DaxEditor/commit/60006e7cfccc72c2fecb8cf4138618465f46fadb

**Comment by TheOpenDataLab** [comment]
HavenDV, I've downloaded the latest version of Dax Editor and am experiencing what I think is the same problem. 

Error while reading measures from file 
Exception stack:
   at DaxEditor.BimFileIntegration.GetMeasuresFromBimFile(String bimFilePath)
   at DaxEditor.DaxEditorPackage.EditAdvancedGetBimFileContentCommandExecute(Object sender, EventArgs e)
--- Inner exception
Exception message:
Error while parsing Xmla.
Message: Method not found: 'Microsoft.AnalysisServices.MajorObject Microsoft.AnalysisServices.Utils.Deserialize(System.Xml.XmlReader, Microsoft.AnalysisServices.MajorObject)'.

**Comment by marcosqlbi** [comment]
How did you download the Dax Editor? We still didn't publish the new version, yet.

**Comment by TheOpenDataLab** [comment]
I first downloaded version from Visual Studio Market Place: 



https://marketplace.visualstudio.com/items?itemName=DAXEditor.DAXEditor



And then downloaded and compiled the repo from github 





---- On Sun, 11 Jun 2017 17:22:17 +0200 Marco Russo &lt;notifications@github.com&gt; wrote ----




How did you download the Dax Editor? We still didn't publish the new version, yet.

**Comment by HavenDV** [comment]
Are you sure that you compiled the desired branch? (Need dev - https://github.com/DaxEditor/DaxEditor/tree/dev)

**Comment by TheOpenDataLab** [comment]
Version 2.0.1703.2601

**Comment by agilmore30** [comment]
Hi

I have the latest version of SSDT 17.1 installed and latest update of Dax Editor from VS tool/extensions, and am getting a similar error:

10/07/2017 5:19:28 PM
DAX Editor version: 2.0.1703.2601
Exception message:
Error while reading measures from file 'C:\Users\a.gilmore\Documents\Git\Money3\M3_Tabular\Model.bim'
Exception stack:
   at DaxEditor.BimFileIntegration.GetMeasuresFromBimFile(String bimFilePath)
   at DaxEditor.DaxEditorPackage.EditAdvancedGetBimFileContentCommandExecute(Object sender, EventArgs e)
--- Inner exception
Exception message:
Error while parsing Xmla.
Message: Method not found: 'Microsoft.AnalysisServices.MajorObject Microsoft.AnalysisServices.Utils.Deserialize(System.Xml.XmlReader, Microsoft.AnalysisServices.MajorObject)'.

**Comment by marcosqlbi** [comment]
Is it happening only for models in 1103 compatibility level, or also for 1200 compatibility level?

**Comment by agilmore30** [comment]
The issue is occurring with a model on compatibility level 1103. I'm not in a position to test 1200, as I don't have an SQL Server 2016 instance to deploy too.

**Comment by marcosqlbi** [comment]
If you use the integrated workspace you can create a model in 1200. Knowing this would be helpful to diagnose the issue. Thanks!

**Comment by agilmore30** [comment]
Hi Marco

Apologies for taking so long to verify this. I can confirm that after
switching to 1200 compatibility mode with integrated workspace, the 'Get
Measures from BIM File' worked.

Interestingly though the syntax highlighting no longer appears. 

thanks - Adam Gilmore



Adam Gilmore
Dimodelo Solutions
w: www.dimodelo.com
m: 0407 698 591
e: agilmore@dimodelo.com

**Comment by HavenDV** [comment]
Can you provide a .dax script for testing/patching? If you can, the most abbreviated non-working version

**Comment by n0012** [comment]
I have the sample problem with Visual Studio 2015, latest SSDT, when working with an 1103 compatibility model.  Stuck at SSAS 2012 BI edition since 14/16 did away with it.
